about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path('', views.index, name='index'),
]

events/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path('', views.index, name='index'),
]

news/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:article_id>/', views.article, name="article"),
    path('edit_list/', login_required(views.IndexView.as_view()), name='edit_list'),
    path('post/<int:pk>/update/', login_required(views.UpdateView.as_view()), name='update'),
    path('create/', login_required(views.NewsCreateView.as_view()), name='create'),
]

top/urls.py
from django.urls import path

from . import views

app_name = "top"

urlpatterns = [
    path('', views.index, name='index'),
]

vision/urls.py
from django.urls import path

from . import views

app_name = "vision"

urlpatterns = [
    path('', views.index, name='index'),
]

templates/html/article_base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Cache-Control" content="no-cache">
  <title>{% block title %}{% endblock %}</title>
  {% load static%}
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/pagination.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/tags.css' %}">
  {% block metadata %} {% endblock %}
</head>

<body>

  <header class="header">
    {% include "menu.html" %}
  </header>

  {% block content %}{% endblock %}
  {% include "footer.html" %}
  {% block script %}{% endblock %}
  <script type="text/javascript" src={% static 'js/menu.js' %}></script>

</body>

</html>

templates/html/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Cache-Control" content="no-cache">
  <title>{% block title %}{% endblock %}</title>
  {% load static%}
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/pagination.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/tags.css' %}">
  {% block metadata %} {% endblock %}
</head>

<body>
  <header class="header">
    {% include "menu.html" %}
    {% if top and top.image %}
    <div class="main-visual">
      <img src="{{ top.image.url }}" alt="{{ top.title }} ">
      <div class="page-name">{{ top.title }}</div>
    </div>
    {% else %}
    <div class="main-provisional-visual">
      <div class="page-name">{{ top.title }}</div>
    </div>
    {% endif %}
  </header>

  {% block content %}{% endblock %}
  {% include "footer.html" %}
  {% block script %}{% endblock %}
  <script type="text/javascript" src={% static 'js/menu.js' %}></script>
</body>

</html>

templates/html/footer.html
{% load static %}

<footer id="footer" class="footer">
    <div class="footer-inner">
        <section class="section address">
            <address>
                <div class="company-name">
                    <p class="name short">MPS</p>
                    <p class="name full">morningprojectsamurai</p>
                </div>
                <p class="address">〒106-0032<br>東京都港区六本木6-1-20 六本木電気ビル 6F</p>
                <p class="tel"><a href="tel:03-6890-2074">03-6890-2074</a></p>
                <p class="mail"><a href="mailto:contact@mpsamurai.com">contact@mpsamurai.com</a></p>
            </address>
        </section>
        <section class="section contact">
            <div class="btn-wrap"><a href="{% url 'contact:index' %}"><img src="{% static 'images/inquiry.png' %}"></a></div>
        </section>
        <section class="section link">
            <div class="title">Link</div>
            <div class="btn-sns-block">
                <div class="btn-wrap"><a href="https://twitter.com/mpsamurai_" target="_blank"><img src="{% static 'images/twitter-logo.png' %}"
                            alt="twitter"></a></div>
                <div class="btn-wrap"><a href="https://www.facebook.com/mpsamurai/?fb_dtsg_ag=AdzRzfO0qRSrHVKdOCWbmgKDV3NYVFnYi--FO7VVvkxJ9A%3AAdxz63AGX8yXcgo-RZOy42-2s29iPBzWwiv-GUaFwFQXGQ"
                        target="_blank"><img src="{% static 'images/facebook-logo.png' %}" alt="facebook"></a></div>
            </div>
            <div class="btn-wrap doorkeeper"><a href="https://mpsamurai.doorkeeper.jp" target="_blank"><img src="{% static 'images/doorkeeper-logo.png' %}"
                        alt="doorkeeper"></a></div>
            <div class="link-block">
                <div class="btn-wrap connpass"><a href="https://mpsamurai.connpass.com/" target="_blank"><img src="{% static 'images/connpass-logo.png' %}"
                            alt="connpass"></a></div>
                <div class="btn-wrap peatix"><a href="https://mpsamurai.peatix.com/" target="_blank"><img src="{% static 'images/peatix-logo.jpg' %}"
                            alt="peatix"></a></div>
            </div>
        </section>
    </div>
</footer>

templates/html/menu.html
<div class="menu">
    <section class="nav-section">
        {% load static %}
        <a href="{% url 'top:index' %}">
            <h1 class="header-logo"><img src="{% static 'images/logo.png' %}" alt="top"></h1>
        </a>
        <nav class="gnav">
            <ul class="gnav-list">
                <li><a href="{% url 'about:index' %}">About</a></li>
                <li><a href="{% url 'message:index' %}">Message</a></li>
                <li><a href="{% url 'news:index' %}">News</a></li>
                <li><a href="{% url 'events:index' %}">Events</a></li>
                <li><a href="{% url 'services:index' %}">Services</a></li>
                <li><a href="{% url 'contact:faq_index' %}">FAQ</a></li>
                <li><a href="{% url 'contact:index' %}">Contact</a></li>
            </ul>
        </nav>
    </section>
</div>

templates/html/news_create.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Cache-Control" content="no-cache">
  <title>{% block title %}{% endblock %}</title>
  {% load static%}
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/pagination.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/tags.css' %}">
  {% block css %}{% endblock %}

  {% block metadata %} {% endblock %}
</head>

<body>
  {% include "menu.html" %}
  {% block content %}{% endblock %}
  {% include "footer.html" %}
  {% block script %}{% endblock %}
  <script type="text/javascript" src={% static 'js/menu.js' %}></script>
</body>

</html>

templates/html/news_update.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Cache-Control" content="no-cache">
  <title>{% block title %}{% endblock %}</title>
  {% load static%}
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/pagination.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/tags.css' %}">
  {% block css %}{% endblock %}

  {% block metadata %} {% endblock %}
</head>

<body>
  {% include "menu.html" %}
  {% block content %}{% endblock %}
  {% include "footer.html" %}
  {% block script %}{% endblock %}
  <script type="text/javascript" src={% static 'js/menu.js' %}></script>
</body>

</html>

templates/html/pagination.html
<ul class="pagination">
  {% if paging.previous %}
  <li>
    <div>
      <a href="?page={{ paging.previous }}#taglist">&lt;</a>
    </div>
  </li>
  {% endif%}

  {% for num in paging.range %}
  {% if paging.current == num %}
  <li class="active">
    <div>
      {{ num }}
    </div>
  </li>
  {% else %}
  <li>
    <div>
      <a href="?page={{ num }}#taglist">{{ num }}</a>
    </div>
  </li>
  {% endif %}
  {% endfor %}
  {% if paging.next %}
  <li>
    <div>
      <a href="?page={{ paging.next }}#taglist">&gt;</a>
    </div>
  </li>
  {% endif %}
</ul>

templates/html/tags.html
<div class="tag-area">
    <p class="title">{{tag_title}}</p>
    <ul class="tag-list">
        {% if flag == "all" %}
            {% if "news" in request.path  %}
            <li class="current">
                <a href='{% url "news:index" %}#taglist'>すべて</a>
            </li>
            {% elif "events" in request.path %}
            <li class="current">
                <a href='{% url "events:index" %}#taglist'>すべて</a>
            </li>
            {% else %}
            <li class="current">
                <a href='{% url "top:index" %}'>すべて</a>
            </li>
            {% endif %}
            {% for tag in tags %}
            <li>
                <a href='?tag={{ tag.name }}#taglist'>{{ tag.name }} </a>
            </li>
            {% endfor %}
        {% elif flag == "part" %}
            {% if "news" in request.path  %}
            <li>
                <a href='{% url "news:index" %}#taglist'>すべて</a>
            </li>
            {% elif "events" in request.path %}
            <li>
                <a href='{% url "events:index" %}#taglist'>すべて</a>
            </li>
            {% else %}
            <li>
                <a href='{% url "top:index" %}'>すべて</a>
            </li>
            {% endif %}

           {% for tag in tags %}
               {% if tag.name in tag_names %}
               <li class="current">
                   <a href='?tag={{ tag.name }}#taglist'>{{ tag.name }} </a>
               </li>
               {% else %}
               <li>
                   <a href='?tag={{ tag.name }}#taglist'>{{ tag.name }} </a>
               </li>
               {% endif %}
            {% endfor %}
        {% else %}
           <li>
               <a href='{% url "top:index" %}'>すべて</a>
           </li>
           {% for tag in tags %}
           <li>
               <a href='?tag={{ tag.name }}#taglist'>{{ tag.name }} </a>
           </li>
           {% endfor %}
        {% endif %}
    </ul>
</div>

templates/html/top_base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Cache-Control" content="no-cache">
  <title>{% block title %}{% endblock %}</title>
  {% load static%}
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/tags.css' %}">
  {% block metadata %} {% endblock %}
</head>

<body>

  <header class="header">
    <div class="main-visual">
      <div class="text">
        Make<br>
        The World<br>
        More<br>
        Exciting<br>
      </div>
    </div>
    {% include "menu.html" %}
  </header>

  {% block content %}{% endblock %}
  {% include "footer.html" %}
  {% block script %}{% endblock %}
  <script type="text/javascript" src={% static 'js/menu.js' %}></script>

</body>

</html>

templates/html/top_message.html
<div class="circle-thumb-wrap">
    <ul class="circle-thumb-list">
        <li>
            <a href="{% url 'message:index' %}">
                <div class="img-wrap"><img src="{{ message.photo.url }}" alt=""></div>
                <h3 class="circle-thumb-list-title">代表挨拶</h3>
            </a>
        </li>
        <li>
            <a href="{% url 'vision:index' %}">
                <div class="img-wrap"><img src="{{ vision.image.url }}" alt=""></div>
                <h3 class="circle-thumb-list-title">Vision</h3>
            </a>
        </li>
    </ul>
</div>