news/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:article_id>/', views.article, name="article"),
    path('edit_list/', login_required(views.IndexView.as_view()), name='edit_list'),
    path('post/<int:pk>/update/', login_required(views.UpdateView.as_view()), name='update'),
    path('create/', login_required(views.NewsCreateView.as_view()), name='create'),
]

top/urls.py
from django.urls import path

from . import views

app_name = "top"

urlpatterns = [
    path('', views.index, name='index'),
]

news/models.py
from django.db import models
from people.models import Employee, Member
from django.utils import timezone
from django.urls import reverse
from common.models import BaseMainVisual

class MainVisual(BaseMainVisual):
    image = models.ImageField(
        upload_to='uploads/news/top/image', null=True, blank=True)

class ArticleTag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Article(models.Model):
    image = models.ImageField(upload_to='uploads/news/article/image', blank=True, null=True)
    thumbnail = models.ImageField(
        upload_to='uploads/news/article/thumbnail', default='', blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(default=timezone.now, blank=True)
    title = models.CharField(max_length=70, default='')
    article = models.TextField(default='')
    employee = models.ManyToManyField(Employee, blank=True)
    member = models.ManyToManyField(Member, blank=True)
    tags = models.ManyToManyField(ArticleTag, blank=True)
    is_topic = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news:edit_list')

class Top(models.Model):
    image = models.ImageField(
        upload_to='uploads/news/top/image', null=True, blank=True)
    title = models.CharField(max_length=32)
    update_at = models.DateField(auto_now=True)
    is_used = models.BooleanField(default=False)

    class Meta:
        ordering = ('-update_at', )

    def __str__(self):
        return self.title

news/forms.py
from django import forms
from .models import Article
from PIL import Image

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['updated_date', 'title', 'article', 'employee', 'member', 'tags', 'is_topic', 'image', 'thumbnail']

news/views.py
import json
from collections import OrderedDict
from PIL import Image

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from .models import Top, Article, ArticleTag
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import generic
from .forms import ArticleForm
from django.views.decorators.csrf import csrf_exempt

def _get_page(list_, page_no, count=9):
    paginator = Paginator(list_, count)
    page_number = page_no
    try:
        page = paginator.page(page_no)
    except (EmptyPage, PageNotAnInteger):
        page_number = 1
        page = paginator.page(page_number)
    return page, int(page_number)


def index(request):
    #import pdb; pdb.set_trace()

    if not request.GET.getlist('tag') or '' in request.GET.getlist('tag'):
        flag = "all"
        tag_names = []
        pages, page_number = _get_page(Article.objects.all().order_by(
                'created_date').reverse(), request.GET.get('page'))
    else:
        flag = "part"
        tag_names = request.GET.getlist('tag')
        tag_id = ArticleTag.objects.filter(name__in=request.GET.getlist('tag'))
        tags_id = [tag_id[i].id for i in range(len(tag_id))]

        if tags_id:
            pages, page_number = _get_page(Article.objects.filter(tags__in=tags_id).order_by(
                'created_date').reverse().distinct(), request.GET.get('page'))
        else:
            pages, page_number = _get_page(Article.objects.all().order_by(
                   'created_date').reverse(), request.GET.get('page'))

    # 前後を合わせて5こ表示する様にする
    display_max = 5
    total = pages.paginator.num_pages
    if page_number < 3:
        # 1, 2の時
        start = 1
        end = display_max if total > display_max else total
    elif page_number + 2 > total:
        # 最後の2つ
        start = total - display_max + 1 if total - display_max >= 1 else 1
        end = total
    else:
        # その他
        start = page_number - 2 if page_number - 2 >= 1 else 1
        end = page_number + 2 if total > page_number + 2 else total

    next_num = None
    pre_num = None
    if pages.has_next():
        next_num = pages.next_page_number()

    if pages.has_previous():
        pre_num = pages.previous_page_number()

    top = Top.objects.filter(is_used=True).first()

    paging = {
        "next": next_num,
        "previous": pre_num,
        "range": range(start, end + 1),
        "current": page_number,
    }

    data = {
        'top': top,
        'page': pages,
        'tags': ArticleTag.objects.all(),
        'paging': paging,
        'flag': flag,
        'tag_names': tag_names,
    }

    return render(request, 'news/index.html', data)


def article(request, article_id):

    tag_names = request.GET.getlist(
        'tag') if request.GET.getlist('tag') else None
    article = get_object_or_404(Article, id=article_id)

    writers = []
    writers.extend(article.employee.all())
    writers.extend(article.member.all())

    pages, page_number = _get_page(
        Article.objects.
        filter(tags__in=article.tags.all()).
        exclude(id=article.id).
        order_by('created_date').
        reverse().
        distinct(), request.GET.get('page'), count=3)

    try:
        article_content = json.dumps(article.article).rstrip("\"").lstrip("\"")
    except (ObjectDoesNotExist):
        article_content = None

    top = Top.objects.filter(is_used=True).first()

    data = {
        'top': top,
        'article': article,
        'writers': writers,
        'pages': pages,
        'article_content': article_content,
        'tag_names': tag_names,
    }

    return render(request, "news/article.html", data)

class IndexView(generic.ListView):
    model = Article
    paginated_by = 5
    template_name = 'news/edit_list.html'

class NewsCreateView(generic.CreateView):
    def get(self, request, *args, **kwargs):
        context = {'form': ArticleForm()}
        return render(request, 'news/create.html', context)

    def post(self, request, *args, **kwargs):
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            article.save()

            json_data_img = self.request.POST.get('hiddenImg', '')
            json_data_thumb = self.request.POST.get('hiddenThumb', '')

            if json_data_img:
                crop_image(article, json_data_img, 'image')
            if json_data_thumb:
                crop_image(article, json_data_thumb, 'thumbnail')
            return redirect('/news/create/')
        return render(request, 'news/create.html', {'form': form})

class UpdateView(generic.edit.UpdateView):
    model =  Article
    form_class = ArticleForm
    template_name = 'news/update.html'

    def form_valid(self, form):
        article = super(ArticleForm, form).save()

        json_data_img = self.request.POST.get('hiddenImg', '')
        json_data_thumb = self.request.POST.get('hiddenThumb', '')

        if json_data_img:
            crop_image(article, json_data_img, 'image')
        if json_data_thumb:
            crop_image(article, json_data_thumb, 'thumbnail')
        return redirect('/news/edit_list/')

def crop_image(obj, json_data, attr):
    cropped_info = json.loads(json_data)
    target = getattr(obj, attr)
    image = Image.open(target)

    cropped_image = image.crop((
        cropped_info['x'],
        cropped_info['y'],
        cropped_info['x'] + cropped_info['w'],
        cropped_info['y'] + cropped_info['h']
    ))

    cropped_image.save(target.path)

news/templates/news/article.html
{% extends "article_base.html" %}

{% block title %}
NEWS
{% endblock %}

{% block metadata %}
{% load static %}
<link rel="stylesheet" href='{% static "news/css/news_detail.css" %}'>
{% endblock %}

{% block content %}
<main class="content">
    <section class="article-section">
        <article class="article">
            <div class="top-img">
                <img src='{{ article.image.url }}' alt="{{ article.title }}">
                <div class="page-name">{{ pageName }}</div>
            </div>
            <div class="article-description">
                <div class="article-wrap">
                    <div class="article-head">
                        <time class="date">{{ article.updated_date | date:"Y/m/d f" }}</time>
                        <h1 class="article-title">{{ article.title }}</h1>
                        <div class="tag-area">
                            <p class="title">トピック</p>
                            <ul class="tag-list">
                                {% for tag in article.tags.all %}
                                {% if tag.name in tag_names %}
                                <li class="current"><a href='{% url "news:index" %}?tag={{ tag.name }}#taglist'>{{
                                    tag.name }} </a></li>
                                {% else %}
                                <li><a href='{% url "news:index" %}?tag={{ tag.name }}#taglist'>{{ tag.name }} </a></li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                            </ul>
                        </div>
                    </div>
                    <div class="article-body">
                        <p id="detail"></p>
                    </div>
                </div>
                <div class="in-charge">
                    <p class="text">この人が書きました</p>
                    {% for writer in writers %}
                    <div class="img-wrap"><img src='{{ writer.image.url }}' alt="{{ writer.name }}"></div>
                    <p class="name">{{ writer.name }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="btn-wrap">
                <a href='{% url "news:index" %}'>NEWSに戻る</a>
            </div>
        </article>
    </section>
    <section class="related-article">
        <div class="tag-area">
            <p class="title">関連記事</p>
        </div>
        <div class="news-card-list">
            {% for page in pages %}
            <article class="news-card-list-item">
                <a href='{% url "news:article" page.id %}'>
                    <div class="img-wrap"><img src='{{ page.image.url }}' alt="{{ page.title }}"></div>
                    <div class="description">
                        <time class="date">{{ page.updated_date|date:"Y/m/d f"}}</time>
                        <h3 class="news-title">{{ page.title|truncatechars:"19" }}</h3>
                        <div class="news-tags-wrap">
                         <div class="news-tags">
                          <div class="tags"></div>
                              {% for tag in page.tags.all %}
                               <li>
                                <a href='{% url "news:index" %}?tag={{ tag.name }}#taglist'>{{ tag.name }}</a>
                               </li>
                              {% endfor %}
                         </div>
                        </div>
                    </div>
                </a>
            </article>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}

{% block script %}
{% load static %}
<script type="text/javascript" src="{% static 'js/marked.min.js' %}"></script>
<script type="text/javascript">
    document.getElementById('detail').innerHTML = marked(`{{ article_content | safe }}`);
</script>
{% endblock %}

news/templates/news/create.html
{% extends "news_update.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'news/css/news_edit.css' %}">
{% endblock %}

{% block content %}

<form action="." method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    {% for field in form %}
        {% if field.html_name == 'image' %}

            <div class="canvas_container">
                <canvas class="canvas"></canvas>
                <img class="base_image" src="{% get_media_prefix %}/{{ field.value }}" alt="">
            </div>

            <div class="btn-wrap choose">{{ field }}</div>

            <div class="slide_bar_container">
                <input class="slide_bar_of_scaling" type="range">
            </div>
            <div class="trim_canvas_container">
                <canvas class="trimming_canvas"></canvas>
            </div>

            <div><input class="coordinate" type="hidden" name="hiddenImg" value=''></div>

        {% elif field.html_name == 'thumbnail' %}

            <div class="canvas_container">
                <canvas class="canvas"></canvas>
                <img class="base_image" src="{% get_media_prefix %}/{{ field.value }}" alt="">
            </div>

            <div class="btn-wrap choose">{{ field }}</div>

            <div class="slide_bar_container">
                <input class="slide_bar_of_scaling" type="range">
            </div>
            <div class="trim_canvas_container">
                <canvas class="trimming_canvas"></canvas>
            </div>

            <div><input class="coordinate" type="hidden" name="hiddenThumb" value=''></div>

        {% elif field.html_name == 'title' %}
            <div class="fields-wrap">
                <div class="fields-title">{{ field.html_name }}：</div>
                <div>{{ field }}</div>
            </div>
        {% elif field.html_name == 'article' %}
            <div class="fields-wrap">
                <div class="fields-title">{{ field.html_name }}：</div>
                <div>{{ field }}</div>
            </div>
        {% elif field.html_name == 'employee' %}
            <div class="fields-wrap">
                <div class="fields-title">{{ field.html_name }}：</div>
                <div>{{ field }}</div>
            </div>
        {% elif field.html_name == 'member' %}
            <div class="fields-wrap">
                <div class="fields-title">{{ field.html_name }}：</div>
                <div>{{ field }}</div>
            </div>
        {% elif field.html_name == 'tags' %}
            <div class="fields-wrap">
                <div class="fields-title">{{ field.html_name }}：</div>
                <div>{{ field }}</div>
            </div>
        {% elif field.html_name == 'is_topic' %}
    <div class="fields-wrap"><div class="fields-title">{{ field.html_name }}：</div>{{ field }}</div>
        {% endif %}
    {% endfor %}

    <div class="btn-wrap submit"><button type="submit">Submit</button></div>
    <script type="text/javascript" src={% static 'js/news_upload.js' %}></script>
</form>

{% endblock %}

news/templates/news/edit_list.html
{% extends "base.html" %}

{% block metadata %}
{% load static %}
<link rel="stylesheet" href='{% static "news/css/news.css" %}'>
<link rel="stylesheet" href='{% static "news/css/news_edit.css" %}'>
{% endblock %}

{% block content %}
<main class="content">
    <div class="news-section">
        <h1>My Articles</h1>
        <section class="post-list">
            <ul class="article-list">
                {% for post in object_list %}
                <li>
                    <p><a href="{% url 'news:update' post.pk %}">{{ post.title }}</a></p>
                </li>
                {% empty %}
                <li class="no-post">
                    <p>No articles yet.</p>
                {% endfor %}
            </ul>
        </section>

        {% if is_paginated %}
        <section class="pagination">
            <ul>
                <li>
                    {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt; Prev</a>
                    {% else %}
                    &lt;&lt; Prev
                    {% endif %}
                </li>
                <li>
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Next &gt;&gt;</a>
                    {% else %}
                    Next &gt;&gt;
                    {% endif %}
                </li>
            </ul>
        </section>
        {% endif %}
    </div>
</main>
{% endblock %}

news/templates/news/index.html
{% extends "base.html" %}

{% block title %}
NEWS
{% endblock %}

{% block metadata %}
{% load static %}
<link rel="stylesheet" href="{% static 'news/css/news.css' %}">
{% endblock %}

{% block content %}
<main class="content">
  <div id="taglist"></div>
  {% with "トピック" as tag_title %}
  {% include "tags.html" %}
  {% endwith %}
  <section class="news-section">
    <div class="news-card-list">
      {% for data in page %}
      <article class="news-card-list-item">
        <a href='{% url "news:article" data.id %}'>
          <div class="img-wrap">
            <img src='{{ data.image.url }}' alt="{{ data.title }}">
          </div>
          <div class="description">
            <time class="date">{{ data.updated_date|date:"Y/m/d f" }}</time>
            <h3 class="news-title">{{ data.title }}</h3>
            <div class="news-tags-wrap">
              <div class="news-tags">
                <div class="tags"></div>
                <ul>
                  {% for tag in data.tags.all %}
                  <li>
                    <a href='?tag={{ tag.name }}#taglist'>{{ tag.name }} </a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </a>
      </article>
      {% endfor %}
    </div>
  </section>
</main>
<div>
  {% include "pagination.html" %}
</div>
{% endblock %}

news/templates/news/update.html
{% extends "news_update.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'news/css/news_edit.css' %}">
{% endblock %}



{% block content %}
<main class="content">

    <section>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}

                {% if field.html_name == 'image' %}

                    <div class="canvas_container">
                        <canvas class="canvas"></canvas>
                        <img class="base_image" src="{% get_media_prefix %}/{{ field.value }}" alt="">
                    </div>

                    <div class="btn-wrap choose">{{ field }}</div>

                    <div class="slide_bar_container">
                        <input class="slide_bar_of_scaling" type="range">
                    </div>
                    <div class="trim_canvas_container">
                        <canvas class="trimming_canvas"></canvas>
                    </div>

                    <div><input class="coordinate" type="hidden" name="hiddenImg" value=''></div>

                {% elif field.html_name == 'thumbnail' %}

                    <div class="canvas_container">
                        <canvas class="canvas"></canvas>
                        <img class="base_image" src="{% get_media_prefix %}/{{ field.value }}" alt="">
                    </div>

                    <div class="btn-wrap choose">{{ field }}</div>

                    <div class="slide_bar_container">
                        <input class="slide_bar_of_scaling" type="range">
                    </div>
                    <div class="trim_canvas_container">
                        <canvas class="trimming_canvas"></canvas>
                    </div>

                    <div><input class="coordinate" type="hidden" name="hiddenThumb" value=''></div>

                {% elif field.html_name == 'title' %}
                    <div class="fields-wrap">
                        <div class="fields-title">{{ field.html_name }}：</div>
                        <div>{{ field }}</div>
                    </div>
                {% elif field.html_name == 'article' %}
                    <div class="fields-wrap">
                        <div class="fields-title">{{ field.html_name }}：</div>
                        <div>{{ field }}</div>
                    </div>
                {% elif field.html_name == 'employee' %}
                    <div class="fields-wrap">
                        <div class="fields-title">{{ field.html_name }}：</div>
                        <div>{{ field }}</div>
                    </div>
                {% elif field.html_name == 'member' %}
                    <div class="fields-wrap">
                        <div class="fields-title">{{ field.html_name }}：</div>
                        <div>{{ field }}</div>
                    </div>
                {% elif field.html_name == 'tags' %}
                    <div class="fields-wrap">
                        <div class="fields-title">{{ field.html_name }}：</div>
                        <div>{{ field }}</div>
                    </div>
                {% elif field.html_name == 'is_topic' %}
            <div class="fields-wrap"><div class="fields-title">{{ field.html_name }}：</div>{{ field }}</div>
                {% endif %}


            {% endfor %}

            <div class="btn-wrap submit"><button type="submit">Submit</button></div>

            <script type="text/javascript" src={% static 'js/news_upload.js' %}></script>
        </form>

    </section>



</main>


{% endblock %}