contact/urls.py
from django.urls import path

from . import views

app_name = "contact"

urlpatterns = [
    path('faqs/', views.faq_index, name='faq_index'),
    path('form/<int:category_id>/', views.form_index, name='form_index'),
    path('form/', views.form_create, name='form_save'),
    path('', views.index, name='index'),
]

top/urls.py
from django.urls import path

from . import views

app_name = "top"

urlpatterns = [
    path('', views.index, name='index'),
]

contact/models.py
from django.db import models
from common.models import BaseMainVisual


class MainVisual(BaseMainVisual):
    image = models.ImageField(
        upload_to='uploads/contact/top/image', null=True, blank=True)


class Category(models.Model):
    name = models.CharField(max_length=64)
    identifier = models.CharField(max_length=64)
    used_status = models.BooleanField(default=False)
    color_code = models.CharField(max_length=16)

    def __str__(self):
        return str(self.name)


class Faq(models.Model):
    question = models.CharField(max_length=1024)
    answer = models.TextField(max_length=1024)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    display_status = models.BooleanField(default=False)

    def __str__(self):
        return str(self.question)


class Contact(models.Model):
    name = models.CharField(max_length=64, verbose_name='名前')
    email = models.EmailField(blank=True, verbose_name='メールアドレス')
    subject = models.CharField(max_length=256, verbose_name='タイトル')
    body = models.TextField(max_length=2048, verbose_name='内容')
    category_name = models.CharField(
        max_length=256, default='その他', verbose_name='カテゴリー名')

    def __str__(self):
        return str(self.name)


class CategoryTop(models.Model):
    image = models.ImageField(
        upload_to='uploads/contact/category/top/image', null=True, blank=True)
    title = models.CharField(max_length=32)
    update_at = models.DateField(auto_now=True)
    is_used = models.BooleanField(default=False)

    class Meta:
        ordering = ('-update_at', )

    def __str__(self):
        return self.title


class FaqTop(models.Model):
    image = models.ImageField(
        upload_to='uploads/contact/faq/top/image', null=True, blank=True)
    title = models.CharField(max_length=32)
    update_at = models.DateField(auto_now=True)
    is_used = models.BooleanField(default=False)

    class Meta:
        ordering = ('-update_at', )

    def __str__(self):
        return self.title


class ContactTop(models.Model):
    image = models.ImageField(
        upload_to='uploads/contact/top/image', null=True, blank=True)
    title = models.CharField(max_length=32)
    update_at = models.DateField(auto_now=True)
    is_used = models.BooleanField(default=False)

    class Meta:
        ordering = ('-update_at', )

    def __str__(self):
        return self.title

contact/views.py
from django.shortcuts import render, redirect

from .models import Faq, Category, ContactTop, FaqTop, CategoryTop
from .form import ContactForm
from django.views.decorators.http import require_POST
from itertools import groupby


def index(request):
    top = ContactTop.objects.filter(is_used=True).first()
    d = {
        'categories': Category.objects.filter(used_status=True),
        'top': top,
    }
    return render(request, "contact/index.html", d)


def faq_index(request):
    faqs_by_category = {}
    for category in Category.objects.filter(used_status=True):
        for key, group in groupby(Faq.objects.filter(display_status=True), (lambda x: x.category.pk is category.pk)):
            if (key):
                for faq in group:
                    if faq.category.pk in faqs_by_category.keys():
                        faqs_by_category[category.pk] = faqs_by_category[faq.category.pk] + [faq]
                    else:
                        faqs_by_category[category.pk] = [faq]
    categories_hash = {}
    top = FaqTop.objects.filter(is_used=True).first()
    d = {}
    for category in Category.objects.filter(used_status=True):
        categories_hash[category.pk] = category
        d = {
            'categories': categories_hash,
            'faqs_by_category': faqs_by_category,
            'top': top,
        }
    return render(request, "contact/faq.html", d)


def form_index(request, **kwargs):
    top = CategoryTop.objects.filter(is_used=True).first()
    input_category_id = kwargs.get('category_id')
    filtered_category = Category.objects.filter(pk=input_category_id)
    category_name = "その他"
    if filtered_category.exists():
        category_name = filtered_category.first().name

    context = {
        'form': ContactForm(initial={'category_name': category_name}),
        'top': top,
    }
    return render(request, "contact/form.html", context)


@require_POST
def form_create(request):
    form = ContactForm(request.POST)

    if form.is_valid():
        form.save()
        return redirect('contact:index')
    context = {
        'form': form
    }
    return render(request, "contact/form.html", context)

contact/templates/contact/faq.html
{% extends "base.html" %}

{% block title %}
FAQ
{% endblock %}

{% block metadata %}
{% load static %}
<link rel="stylesheet" href="{% static 'contact/index.css' %}">
{% endblock %}

{% block content %}

<main class="content">
    <section class="faq-section">
        <h2 class="section-title">よくある質問</h2>
        {% load filter %}
        {% for key, faqs in faqs_by_category.items %}

        <h4 id="{{ categories|categories_identifier_hash:key }}">{{ categories|categories_name_hash:key }}</h4>

        <div class="faq-list-wrap">
            <div class="faq-list">
                {% for faq in faqs %}
                <dl class="faq-list-item question">
                    <dt>Q</dt>
                    <dd>{{ faq.question | linebreaksbr}}</dd>
                </dl>
                <dl class="faq-list-item answer">
                    <dt>A</dt>
                    <dd>{{ faq.answer | linebreaksbr}}</dd>
                </dl>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </section>
</main>


{% endblock %}

contact/templates/contact/form.html
{% extends "base.html" %}

{% block title %}
お問い合わせ
{% endblock %}

{% block metadata %}
{% load static %}
<link rel="stylesheet" href="{% static 'contact/index.css' %}">
{% endblock %}

{% block content %}
<main class="content">
    <section class="contact-section-form">
        <h2 class="page-title">お問い合わせ</h2>
        <form action="{% url 'contact:form_save' %}" method="POST" accept-charset="utf-8">
            <table class="contact-table">
                {% for field in form %}
                <tr>
                    <th>{{ field.label_tag }}
                        {% if not field.label == "" %}<span class="annotation">*</span>{% endif %}
                    </th>
                    <td>{{ field }}</td>
                </tr>
                {% endfor %}
            </table>
            {% csrf_token %}
            <div class="btn-wrap">
                <button class="btn-submit" type="submit">送信</button>
            </div>
        </form>
    </section>
</main>

{% endblock %}

contact/templates/contact/index.html
{% extends "base.html" %}

{% block title %}
お問い合わせ
{% endblock %}

{% block metadata %}
{% load static %}
<link rel="stylesheet" href="{% static 'contact/index.css' %}">
{% endblock %}


{% block content %}

<main class="content">
    <section class="contact-section">
        <ul class="contact-list">
            {% for category in categories %}
            <li class="{{ category.identifier }}">
                <div class="top-panel" style="background-color : {{ category.color_code}}">
                    <p class="title">{{ category.name }}</p>
                </div>
                <a class="btn" href="{% url 'contact:faq_index' %}#{{  category.identifier  }}">よくある質問</a>
                <a class="btn" href="{% url 'contact:form_index' category_id=category.pk %}">お問い合わせ</a>
            </li>
            {% endfor %}
        </ul>
    </section>
</main>

{% endblock %}